crud/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.views.static import serve
from django.conf import settings

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', 'students.views.homepage', name='homepage'),
    url(r'student/', include('students.urls')),
    url(r'^media/(?P<path>.*)', serve, {"document_root": settings.MEDIA_ROOT})
]

students/urls.py
from django.conf.urls import url

urlpatterns = [
    url(r'^(?P<username>\w+)/$', 'students.views.profile', name='profile'),
    url(r'^(?P<username>\w+)/edit/$', 'students.views.edit_student', name='edit_student'),
    url(r'^delete-student/$', 'students.views.delete_student', name='delete_student'),
    url(r'^create-student/$', 'students.views.create_student', name='create_student'),
]

students/models.py
from __future__ import unicode_literals

from django.db import models
from django.conf import settings
from django_countries.fields import CountryField
from django.core.urlresolvers import reverse
from django.contrib.auth.models import User
from django.contrib.contenttypes.models import ContentType

GENDER_CHOICES = (
    ('Male', 'Male'),
    ('Female', 'Female'),
    ('Others', 'Others'),
)

class Student(models.Model):
    user = models.ForeignKey(User)
    avatar = models.ImageField(upload_to="profile/editors/", null=True, blank=True)
    address = models.CharField(max_length=60, blank=True, null=True)
    nationality = models.CharField(max_length=255, blank=True, null=True)
    gender = models.CharField(max_length=60, null=True, blank=True, choices=GENDER_CHOICES)
    country = CountryField(blank_label="(select country)", null=True, blank=True)

    def __str__(self):
        return u'%s %s' %(self.user.first_name, self.user.last_name)

students/forms.py
from __future__ import unicode_literals
from datetime import datetime

from django import forms
from django.conf import settings
from django.forms import FileInput
from django_countries import countries
from django.contrib.auth.models import User
from students.models import Student


class EditStudentForm(forms.ModelForm):
    first_name = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control', 'required': 'required'}))
    last_name = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control', 'required': 'required'}))
    email = forms.EmailField(widget=forms.TextInput(attrs={'class': 'form-control', 'type': 'email', 'required': 'required'}))

    class Meta:
        model=Student
        exclude = ['user']
        widgets = {
            'avatar': FileInput(),
        }

    def __init__(self, *args, **kwargs):
        super(EditStudentForm, self).__init__(*args, **kwargs)
        self.fields['gender'].widget.attrs.update({'class': 'form-control', 'required': 'required'})
        self.fields['address'].widget.attrs.update({'class': 'form-control'})
        self.fields['country'].widget.attrs.update({'class': 'form-control'})
        self.fields['nationality'].widget.attrs.update({'class': 'form-control'})

class CreateStudentForm(forms.ModelForm):
    pass        

students/views.py
import json

from django.shortcuts import render
from django.shortcuts import render_to_response, redirect
from django.template import RequestContext
from students.models import Student
from django.contrib.auth.models import User
from django.http import HttpResponse
from django.db.models import Q
from django.forms.models import model_to_dict


from django.core.urlresolvers import reverse
from students.forms import EditStudentForm
from students.utils import create_username


# Create your views here.
def homepage(request):
    students = Student.objects.all()
    query = request.GET.get('q', '')
    if query:
        students = students.filter(
            Q(user__first_name__icontains=query) |
            Q(user__last_name__icontains=query)
        )

    return render_to_response("student/homepage.html", {
        'query': query,
        'current': 'homepage',
        'students': students
    }, context_instance=RequestContext(request))


def profile(request, username):
    student = Student.objects.get(user__username=username)

    return render_to_response("student/profile.html",{
    'student':student
    }, context_instance=RequestContext(request))


def edit_student(request, username):
    student= Student.objects.get(user__username=username)

    if request.method == "POST":
        form = EditStudentForm(request.POST, request.FILES, instance=student)

        if form.is_valid():
            obj = form.save(commit=False)
            obj.user.first_name = form.cleaned_data["first_name"]
            obj.user.last_name = form.cleaned_data["last_name"]
            obj.user.email = form.cleaned_data["email"]
            obj.user.save()
            obj.save()

            return redirect(reverse("profile", kwargs={"username": student.user.username}))

        return render_to_response("student/edit_student",{
            "student": student,
            "form": form,
        }, context_instance=RequestContext(request))

    else:
        form = EditStudentForm(instance=student, initial={
            'first_name': student.user.first_name,
            'last_name': student.user.last_name,
            'email': student.user.email
        })

        return render_to_response("student/edit_student.html",{
            "form": form,
            "student": student
        }, context_instance=RequestContext(request))


def delete_student(request):

    if request.is_ajax():

        response = {"status": False, "errors": []}

        student_id = request.GET.get('student_id', '')

        student = Student.objects.get(id=student_id)

        student_id= student.id
        response["student_deleted"] = model_to_dict(student, fields=['username', 'id'])

        student.user.delete()

        
        response["status"] = True

        return HttpResponse(json.dumps(response))  
        


def create_student(request):
    if request.method == "POST":
        form = EditStudentForm(request.POST, request.FILES)

        if form.is_valid():
            user = User.objects.create(
                username=create_username('%s %s' % (form.cleaned_data["first_name"], form.cleaned_data["last_name"])),
                first_name=form.cleaned_data["first_name"],
                last_name=form.cleaned_data["last_name"],
                email=form.cleaned_data["email"],
            )

            student = Student.objects.create(
                user=user,
                gender=form.cleaned_data["gender"],
                address=form.cleaned_data["address"],
                country=form.cleaned_data["country"],
                nationality=form.cleaned_data["nationality"]
            )

            if request.FILES:
                student.avatar = request.FILES.get("avatar")
            student.save()

            return redirect("/")
    else:
        form = EditStudentForm()

    return render_to_response("student/edit_student.html", {
        "form": form,
        "current": "signup"
    }, context_instance=RequestContext(request))

templates/base.html
{% load staticfiles %}

<!DOCTYPE html>
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>Crud</title>
        <link href="{% static 'css/font-awesome-4.7.0/css/font-awesome.min.css' %}" rel="stylesheet">
        <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
        <link href="{% static 'css/custom.css' %}" rel="stylesheet">
        <link href="{% static 'css/select2.min.css' %}" rel="stylesheet">
    </head>
    <body style="background-color: #C09FD6;padding-top: 70px;">
        <nav class="navbar navbar-default navbar-fixed-top" style="border-radius:0px">
            <div class="container-fluid">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a class="navbar-brand" href="/">Crud Application</a>
                </div>
            </div>
        </nav>
        <div class="main-content">
            {% block content %}
            {% endblock %}
        </div>

        <!-- Core Scripts - Include with every page -->
        <script src = "{% static 'js/jquery-1.11.2.min.js' %}"></script>
        <script src = "{% static 'js/jquery.min.js' %}"></script>
        <script src = "{% static 'js/bootstrap.min.js' %}"></script>
        <!-- <script src = "{% static 'js/modal.js' %}"></script> -->
        <script src = "{% static 'js/validator.js' %}"></script>
        <script src = "{% static 'js/select2.min.js' %}"></script>
        <script src = "{% static 'js/select2.full.min.js' %}"></script>
        <script src = "{% static 'js/validator.js' %}"></script>
        <script src="{% static 'js/custom.js' %}"></script>
        <script type="text/javascript">
        Window.base = {
            "urls": {
                "delete_student": "{% url 'delete_student' %}",
            }
        }
        </script>
        {% block javascript %}
        {% endblock %}
    </body>
</html>

templates/student/edit_student.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block content %}
    <div class="container" style="width:50%">
        <div class="row">
            <div class="panel panel-default">
                <div class="panel-heading" style="background-color: #2C3E50">
                    <h3 class="panel-title" style="color: white;">Edit Profile</h3>
                </div>
                <form class="form-horizontal" role="form" data-toggle="validator" method="post" enctype="multipart/form-data">
                    {% csrf_token %}
                    <div class="row">
                        <div class="col-md-12">
                            <div class="panel-body" style="margin-top: -10px;">
                                <div class="row">
                                    <div class="col-md-12">
                                        <div class="form-group {% if form.first_name.errors %}has-error{% endif %}" style="margin-bottom: -10px;">
                                            <div class="col-md-12">
                                                <label for="id_first_name" class="control-label">*First Name:</label>
                                                {{ form.first_name }}
                                                <small class="error">{{ form.first_name.errors.as_text }}</small>
                                                <small class="help-block with-errors"></small>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                <div class="row">
                                    <div class="col-md-12">
                                        <div class="form-group {% if form.last_name.errors %}has-error{% endif %}">
                                            <div class="col-md-12">
                                                <label for="id_last_name" class="control-label">*Last Name:</label>
                                                {{ form.last_name }}
                                                <small class="error">{{ form.last_name.errors.as_text }}</small>
                                                <small class="help-block with-errors"></small>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                <div class="row">
                                    <div class="col-md-12">
                                        <div class="form-group {% if form.email.errors %}has-error{% endif %}" style="margin-top: -20px;">
                                            <div class="col-md-12" >
                                                <label for="id_email" class="control-label">*Email:</label>
                                                {{ form.email }}
                                                <small class="error">{{ form.email.errors.as_text }}</small>
                                                <small class="help-block with-errors"></small>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                <div class="row">
                                    <div class="col-md-12">
                                        <div class="form-group {% if form.gender.errors %}has-error{% endif %}" style="margin-top: -20px;">
                                            <div class="col-md-12" >
                                                <label for="id_gender" class="control-label">Gender:</label>
                                                {{ form.gender }}
                                                <small class="error">{{ form.gender.errors.as_text }}</small>
                                                <small class="help-block with-errors"></small>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                <div class="row">
                                    <div class="col-md-12">
                                        <div class="form-group {% if form.address.errors %}has-error{% endif %}" style="margin-top: -20px;">
                                            <div class="col-md-12" >
                                                <label for="id_address" class="control-label">Address:</label>
                                                {{ form.address }}
                                                <small class="error">{{ form.address.errors.as_text }}</small>
                                                <small class="help-block with-errors"></small>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                <div class="row">
                                    <div class="col-md-12">
                                        <div class="form-group" style="margin-top: -20px;">
                                            <div class="col-md-12">
                                                <label for="id_country" class="control-label">Country:</label>
                                                {{ form.country }}
                                                {{ form.country.errors.as_text }}
                                                <div class="help-block with-errors"></div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                <div class="row">
                                	<div class="col-md-12">
                                        <div class="form-group" style="margin-top: -20px;">
                                            <div class="col-md-12">
                                                <label for="id_nationality" class="control-label">Nationality:</label>
                                                {{ form.nationality }}
                                                {{ form.nationality.errors.as_text }}
                                                <div class="help-block with-errors"></div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                <div class="row">
                                    <div class="col-md-12">
                                        <div class="form-group" style="margin-top: -20px; margin-bottom: -10px;">
                                            <div class="col-md-12">
                                                <label for="id_avatar" class="control-label" style="cursor: pointer;">Avatar:</label>
                                                <div class="thumbnail" style="width: 100px; cursor: pointer;">
                                                    <div id="id_avatar_img" class="thubmnail-inner img-rounded">
                                                        <img src="{% if student.avatar %}{{ student.avatar.url }}{% else %}{% static 'images/nodp.jpg' %}{% endif %}" class="" alt="Cinque Terre">
                                                    </div>
                                                </div>
                                                {{ form.avatar }}
                                                {{ form.avatar.errors.as_text }}
                                                <small class="help-block with-errors"></small>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-12">
                            <div class="form-group">
                                <div class="col-md-12">
                                    <input class="btn btn-primary btn-sm" type="submit" value="Save"/ style="width: 80px; margin-left: 15px;">
                                </div>
                            </div>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
{% endblock %}

{% block javascript %}
    <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap-tagsinput.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap-tagsinput-typeahead.css' %}">
    <script src="{% static 'js/bloodhound.min.js' %}" ></script>
    <script src="{% static 'js/bootstrap-typeahead.js' %}"></script>
    <script src="{% static 'js/bootstrap-tagsinput.js' %}"></script>
    <script type="text/javascript">
        $(function() {
            $("#id_avatar").on('change', function () {
                var image_holder = $("#id_avatar_img");
                image_holder.empty();
                var reader = new FileReader();
                reader.onload = function (e) {
                    $("<img />", {
                        "src": e.target.result
                    }).appendTo(image_holder);

                }
                image_holder.show();
                reader.readAsDataURL($(this)[0].files[0]);
            });

            $("#id_avatar").css("display", "none");
            $("#id_avatar_img").on("click", function(){
                $("#id_avatar").trigger("click");
            })

        })
    </script>
{% endblock %}

templates/student/homepage.html
{% extends 'base.html' %}

{% load staticfiles %}

{% block javascript %}
    <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap-tagsinput.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap-tagsinput-typeahead.css' %}">
    <script src="{% static 'js/bloodhound.min.js' %}" ></script>
    <script src="{% static 'js/bootstrap-typeahead.js' %}"></script>
    <script src="{% static 'js/bootstrap-tagsinput.js' %}"></script>
    <script src="{% static 'js/jquery.jtruncate.js' %}"></script>
    <script type="text/javascript">

        var deleted_id = '';

        function delete_notify(student_id){
            $("#id_delete_confirm").attr("onclick", "delete_student(" + student_id + ")");
            $("#id_delete_message").text("Do you really want to delete this Student?");
            $("#id_delete_modal").modal("show");
        };
        function delete_student(student_id){
            $.ajax({
                url: Window.base.urls.delete_student+"?student_id="+student_id,
                type: "GET",
                success: function(response){
                    response = JSON.parse(response);

                    if(response.status){
                        debugger;
                        deleted_id = response.student_deleted.id;
                        $("#id_student_"+deleted_id).remove();
                        $("#id_delete_modal").modal("hide");
                    }
                }
            });
            return false;
        }
    </script>
{% endblock %}

{% block content %}
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-10 col-md-offset-1 paddingtop-20 profile-block">
                <h3><center><strong>Student List</strong></center></h3>
                <a href="{% url 'create_student' %}" id="add_student" class="btn btn-default btn-sm pull-right" style="background-color: #2C3E50; margin-top:-40px;">
                    <span class="glyphicon glyphicon-plus" style="color: white;"></span> Add
                </a>
                <br>
                <br>
                <form method="GET" action="" id="id_student_search">
                    <div class="form-group">
                        <div class="es-form-control">
                            <span class="glyphicon glyphicon-search"></span>
                            <input type="text" class="studentnameinput" name="q" id="id_studentquery" value="{{ query }}" placeholder="Search Students" autocomplete="off" style="width:80%;">
                        </div>
                    </div>
                </form>
                {% if students %}
                    <table class="table">
                        <thead class="thead-default">
                            <tr style="height: 50px;">
                                <th><strong>#</strong></th>
                                <th>Name</th>
                                <th>Email</th>
                                <th>Address</th>
                                <th>Gender</th>
                                <th>Nationality</th>
                                <th>Country</th>
                                <th>Action</th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for student in students %}
                            <tr id="id_student_{{ student.id }}">
                                <th class="col-md-1 gap" scope="row">{{ forloop.counter }}</th>
                                <td class="col-md-2 gap">
                                    <a href="{% url 'profile' student.user.username %}" style="text-decoration:none; color:blue;">{{ student.user.get_full_name }}</a>
                                </td>
                                <td class="col-md-2 gap">{{ student.user.email }}</td>
                                <td class="col-md-3 gap">{{ student.address }}</td>
                                <td class="col-md-1 gap">{{ student.gender }}</td>
                                <td class="col-md-1 gap">{{ student.nationality }}</td>
                                <td class="col-md-1 gap">{{ student.get_country_display }}</td>
                                <td class="col-md-1 gap">
        							<a href="{% url 'edit_student' student.user.username %}" style="cursor:pointer;"><span class="glyphicon glyphicon-pencil" style="color:skyblue"></span></a>
                                    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<a style="cursor:pointer;" onclick="delete_notify('{{ student.id }}');"><span class="glyphicon glyphicon-trash" style="color:red"></span></a>
                                </td>
                            </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                {% else %}
                    <div class="text-muted text-center">No student found.</div>
                {% endif %}
            </div>
        </div>
    </div>
    <!-- Delete Modal -->
    <div id="id_delete_modal" class="modal fade" tabindex="-1" role="dialog">
       <div class="modal-dialog" role="document">
          <div class="modal-content">
             <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title">Notification</h4>
             </div>
             <div class="modal-body">
                <p id="id_delete_message"></p>
             </div>
             <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                <button id="id_delete_confirm" type="button" class="btn btn-primary">Delete</button>
             </div>
          </div>
          <!-- /.modal-content -->
       </div>
       <!-- /.modal-dialog -->
    </div>
    <!-- /.modal -->
{% endblock %}

templates/student/profile.html
{% extends 'base.html' %}

{% load staticfiles %}

{% block content %}
    <div class="container-fluid">
        <div class="col-md-10 col-md-offset-1">
            <div class="row" style="margin-top: -10px;">
                <div class="col-sm-3" >
                    <div class="profile-block">
                        <div class="thumbnail">
                            <img src="{% if student.avatar %}{{ student.avatar.url }}
                            {% else %}{% static 'images/nodp.jpg' %}{% endif %}"
                            alt="{{ student.user.get_full_name }}" style="height: 200px; width: 240px;">
                        </div>
                    </div>
                </div>
                <div class="col-sm-9">
                    <div class = "profile-block" style="text-align:center;">
                        <p style="font-size:25px;"><a style="text-decoration:none;">{{ student.user.get_full_name }}</a></p>
                        {% if student.nationality %}
                            <p><b>Nationality:</b> &nbsp;{{ student.nationality }}</p>
                        {% endif %}
                        {% if student.country %}
                            <p><b>Country:</b> &nbsp;{{ student.country.name }}</p>
                        {% endif %}
                        {% if student.country %}
                            <p><b>Gender:</b> &nbsp;{{ student.gender }}</p>
                        {% endif %}
                    </div>
                </div>
            </div>
        </div>
    </div>

{% endblock %}

{% block javascript %}

	<script type="text/javascript">

    </script>

{% endblock %}